//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.09 at 11:34:16 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ftn.uns.ac.rs/nalog", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nalog;

