//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.13 at 06:06:03 PM CEST 
//

package zahtevZaIzvod;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for zahtevZaIzvod complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="zahtevZaIzvod">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="brojRacuna" type="{http://ftn.uns.ac.rs/tipovi}tipRacun"/>
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="rbrPreseka">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;totalDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zahtevZaIzvod", propOrder = { "brojRacuna", "datum",
		"rbrPreseka" })
public class ZahtevZaIzvod {

	@XmlElement(required = true)
	protected String brojRacuna;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar datum;
	@XmlElement(required = true)
	protected BigInteger rbrPreseka;

	/**
	 * Gets the value of the brojRacuna property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBrojRacuna() {
		return brojRacuna;
	}

	/**
	 * Sets the value of the brojRacuna property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBrojRacuna(String value) {
		this.brojRacuna = value;
	}

	/**
	 * Gets the value of the datum property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getDatum() {
		return datum;
	}

	/**
	 * Sets the value of the datum property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDatum(XMLGregorianCalendar value) {
		this.datum = value;
	}

	/**
	 * Gets the value of the rbrPreseka property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getRbrPreseka() {
		return rbrPreseka;
	}

	/**
	 * Sets the value of the rbrPreseka property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setRbrPreseka(BigInteger value) {
		this.rbrPreseka = value;
	}

}
