
package rs.ac.uns.ftn.cb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import rs.ac.uns.ftn.mt102.Mt102;
import rs.ac.uns.ftn.mt103.Mt103;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CentralnaBankaServis", targetNamespace = "http://ftn.uns.ac.rs/CB")
@XmlSeeAlso({
    rs.ac.uns.ftn.cb.ObjectFactory.class,
    rs.ac.uns.ftn.mt102.ObjectFactory.class,
    rs.ac.uns.ftn.mt103.ObjectFactory.class
})
public interface CentralnaBankaServis {


    /**
     * 
     * @param mt102
     */
    @WebMethod
    @RequestWrapper(localName = "primiMt102", targetNamespace = "http://ftn.uns.ac.rs/mt102", className = "rs.ac.uns.ftn.mt102.PrimiMt102")
    @ResponseWrapper(localName = "primiMt102Response", targetNamespace = "http://ftn.uns.ac.rs/CB", className = "rs.ac.uns.ftn.cb.PrimiMt102Response")
    @Action(input = "http://ftn.uns.ac.rs/CB/CentralnaBankaServis/primiMt102Request", output = "http://ftn.uns.ac.rs/CB/CentralnaBankaServis/primiMt102Response")
    public void primiMt102(
        @WebParam(name = "mt102", targetNamespace = "http://ftn.uns.ac.rs/mt102")
        Mt102 mt102);

    /**
     * 
     * @param mt103
     */
    @WebMethod
    @RequestWrapper(localName = "primiMt103", targetNamespace = "http://ftn.uns.ac.rs/mt103", className = "rs.ac.uns.ftn.mt103.PrimiMt103")
    @ResponseWrapper(localName = "primiMt103Response", targetNamespace = "http://ftn.uns.ac.rs/CB", className = "rs.ac.uns.ftn.cb.PrimiMt103Response")
    @Action(input = "http://ftn.uns.ac.rs/CB/CentralnaBankaServis/primiMt103Request", output = "http://ftn.uns.ac.rs/CB/CentralnaBankaServis/primiMt103Response")
    public void primiMt103(
        @WebParam(name = "mt103", targetNamespace = "http://ftn.uns.ac.rs/mt103")
        Mt103 mt103);

}
