
package generisani;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CentralnaBankaServis", targetNamespace = "http://ftn.uns.ac.rs/CB", wsdlLocation = "http://SarvanLaptop:1080/CentralnaBanka/CentralnaBankaServis?wsdl")
public class CentralnaBankaServis_Service
    extends Service
{

    private final static URL CENTRALNABANKASERVIS_WSDL_LOCATION;
    private final static WebServiceException CENTRALNABANKASERVIS_EXCEPTION;
    private final static QName CENTRALNABANKASERVIS_QNAME = new QName("http://ftn.uns.ac.rs/CB", "CentralnaBankaServis");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://SarvanLaptop:1080/CentralnaBanka/CentralnaBankaServis?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CENTRALNABANKASERVIS_WSDL_LOCATION = url;
        CENTRALNABANKASERVIS_EXCEPTION = e;
    }

    public CentralnaBankaServis_Service() {
        super(__getWsdlLocation(), CENTRALNABANKASERVIS_QNAME);
    }

    public CentralnaBankaServis_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CENTRALNABANKASERVIS_QNAME, features);
    }

    public CentralnaBankaServis_Service(URL wsdlLocation) {
        super(wsdlLocation, CENTRALNABANKASERVIS_QNAME);
    }

    public CentralnaBankaServis_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CENTRALNABANKASERVIS_QNAME, features);
    }

    public CentralnaBankaServis_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CentralnaBankaServis_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CentralnaBankaServis
     */
    @WebEndpoint(name = "CentralnaBanka")
    public CentralnaBankaServis getCentralnaBanka() {
        return super.getPort(new QName("http://ftn.uns.ac.rs/CB", "CentralnaBanka"), CentralnaBankaServis.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CentralnaBankaServis
     */
    @WebEndpoint(name = "CentralnaBanka")
    public CentralnaBankaServis getCentralnaBanka(WebServiceFeature... features) {
        return super.getPort(new QName("http://ftn.uns.ac.rs/CB", "CentralnaBanka"), CentralnaBankaServis.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CENTRALNABANKASERVIS_EXCEPTION!= null) {
            throw CENTRALNABANKASERVIS_EXCEPTION;
        }
        return CENTRALNABANKASERVIS_WSDL_LOCATION;
    }

}
