
package generisani;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CentralnaBankaServis", targetNamespace = "http://ftn.uns.ac.rs/CB")
//@XmlSeeAlso({
  //  ObjectFactory.class
//})
public interface CentralnaBankaServis {


    /**
     * 
     * @param mt103
     */
    @WebMethod
    @RequestWrapper(localName = "primiMt103", targetNamespace = "http://ftn.uns.ac.rs/mt103", className = "generisani.PrimiMt103")
    @ResponseWrapper(localName = "primiMt103Response", targetNamespace = "http://ftn.uns.ac.rs/CB", className = "generisani.PrimiMt103Response")
    @Action(input = "http://ftn.uns.ac.rs/CB/CentralnaBankaServis/primiMt103Request", output = "http://ftn.uns.ac.rs/CB/CentralnaBankaServis/primiMt103Response")
    public void primiMt103(
        @WebParam(name = "mt103", targetNamespace = "http://ftn.uns.ac.rs/mt103")
        Mt103 mt103);

    /**
     * 
     * @param mt102
     */
    @WebMethod
    @RequestWrapper(localName = "primiMt102", targetNamespace = "http://ftn.uns.ac.rs/mt102", className = "generisani.PrimiMt102")
    @ResponseWrapper(localName = "primiMt102Response", targetNamespace = "http://ftn.uns.ac.rs/CB", className = "generisani.PrimiMt102Response")
    @Action(input = "http://ftn.uns.ac.rs/CB/CentralnaBankaServis/primiMt102Request", output = "http://ftn.uns.ac.rs/CB/CentralnaBankaServis/primiMt102Response")
    public void primiMt102(
        @WebParam(name = "mt102", targetNamespace = "http://ftn.uns.ac.rs/mt102")
        Mt102 mt102);
    

}
